
######################## default configuration ####################
baseURL = "https://sg.com.mx/dataday/"
publishDir = "public/dataday"
title = "Data Day MTY"
enableRobotsTXT = true
RemovePathAccents = true


googleAnalytics = "G-7XSYNH098S"

theme = "dataday"
# post pagination
paginate = "10"

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


############################## navigation ###############################
[menu]


  [[menu.main]]
  name = "Acerca de"
  URL = "about-us"
  weight = 1

  [[menu.main]]
  name = "Sesiones anteriores"
  URL = "/sessions"
  weight = 2

  [[menu.main]]
  name = "Conferencistas"
  URL = "speakers"
  weight = 3

  [[menu.main]]
  name = "Organizadores"
  URL = "team"
  weight = 3



  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 6




#################### default parameters ################################
[params]
logo = "images/dataday2022.png"
home = "Home"

# Meta data
description = "Data Day es el congreso líder de ciencia e ingeniería de datos. La próxima edición es el 14 de noviembre de 2023 en Monterrey."
image = "images/card-2023mty.jpg"
images = ["images/card-2023mty.jpg"]
twitter_user = "@revistasg"
email = "eventos@sg.com.mx"
author = "Software Guru"
disclaimer = ""

start_date = "2023-11-14T8:30-06:00"
end_date = "2023-11-14T18:00-06:00"

[params.venue]
name = "Escuela de Gobierno y Transformación Pública"
street = "Eugenio Garza Lagüera y, Av. Rufino Tamayo"
city = "San Pedro Garza García"
region = "NL"
zipcode = "66269"
country = "Mexico"

# Navigation button
[params.navigation_button]
enable = true
label = "Mantente informado"
link = "https://cdn.forms-content.sg-form.com/c636d801-8d4d-11ee-bff8-1e7a5c02829b"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/RevistaSG"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/c/softwareguru"

[[params.social]]
icon = "tf-ion-social-octocat"
link = "https://github.com/softwareguru"

[[params.social]]
icon = "tf-ion-android-mail"
link = "mailto:eventos@sg.com.mx"




############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "/plugins/flaticon/flaticon.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.slim.min.js" 

[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="https://kit.fontawesome.com/2e09285ae6.js"

[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"

