
######################## default configuration ####################
baseURL = "https://sg.com.mx/dataday/"
publishDir = "public/dataday"
title = "Data Day MTY"
enableRobotsTXT = true
RemovePathAccents = true

theme = "dataday"
# post pagination

[services]
  [services.googleAnalytics]
    id = 'G-7XSYNH098S'

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


############################## navigation ###############################
[menu]


  [[menu.main]]
  name = "Acerca de"
  URL = "about-us"
  weight = 1

  #[[menu.main]]
  #name = "Agenda"
  #URL = "agenda"
  #weight = 2

  [[menu.main]]
  name = "Conferencistas"
  URL = "speakers"
  weight = 3

  [[menu.main]]
  name = "Organizadores"
  URL = "team"
  weight = 3

  [[menu.main]]
  name = "Patrocinios"
  URL = "patrocinios"
  weight = 5

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 6


#################### default parameters ################################
[params]
logo = "images/dataday2022.png"
home = "Home"

# Meta data
description = "Data Day es el congreso líder de ciencia e ingeniería de datos. La próxima edición es el 14 de noviembre de 2023 en Monterrey."
image = "images/card-2024mty.jpg"
images = ["images/card-2024mty.jpg"]
twitter_user = "@revistasg"
email = "eventos@sg.com.mx"
author = "Software Guru"
disclaimer = ""

start_date = "2024-11-05T8:30-06:00"
end_date = "2024-11-05T18:00-06:00"

[params.venue]
name = "Escuela de Gobierno y Transformación Pública"
street = "Eugenio Garza Lagüera y, Av. Rufino Tamayo"
city = "San Pedro Garza García"
region = "NL"
zipcode = "66269"
country = "Mexico"

# Navigation button
[params.navigation_button]
enable = true
label = "Tickets"
link = "/dataday/tickets"


############################# social icon ############################
[[params.social]]
icon = "fa-brands fa-x-twitter"
link = "https://x.com/RevistaSG"

[[params.social]]
icon = "bi bi-youtube"
link = "https://www.youtube.com/c/softwareguru"

[[params.social]]
icon = "fa-brands fa-instagram"
link = "https://instagram.com/revistasg"

[[params.social]]
icon = "fa-brands fa-facebook"
link = "https://www.facebook.com/softwareguru/"

[[params.social]]
icon = "fa-brands fa-linkedin"
link = "https://www.linkedin.com/company/softwareguru/"

[[params.social]]
icon = "tf-ion-android-mail"
link = "mailto:dataday@sg.com.mx"



############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "/plugins/flaticon/flaticon.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css"

[[params.plugins.css]]
link = "/dataday/css/fontawesome.css"
[[params.plugins.css]]
link = "/dataday/css/brands.css"
[[params.plugins.css]]
link = "/dataday/css/solid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.slim.min.js" 

[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"


[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.js"

