
######################## default configuration ####################
baseURL = "https://sg.com.mx/dataday/"
publishDir = "public/dataday"
title = "Data Day"
enableRobotsTXT = true
RemovePathAccents = true


googleAnalytics = "UA-21077034-25"

theme = "dataday"
# post pagination
paginate = "10"

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


############################## navigation ###############################
[menu]


  [[menu.main]]
  name = "Acerca de"
  URL = "about-us"
  weight = 1


  [[menu.main]]
  name = "On Demand"
  URL = "https://sg.com.mx/dataday/sessions/monterrey-2022/"
  weight = 2

  [[menu.main]]
  name = "Conferencistas"
  URL = "speakers"
  weight = 3


  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 6




#################### default parameters ################################
[params]
logo = "images/dataday2022.png"
home = "Home"

# Meta data
description = "Data Day es el congreso líder de ciencia e ingeniería de datos. La próxima edición es el 26 de abril de 2023."
image = "images/dataday-card-2023.jpg"
images = ["images/dataday-card-2023.jpg"]
twitter_user = "@revistasg"
email = "eventos@sg.com.mx"
author = "Software Guru"
disclaimer = ""

start_date = "2022-12-01T8:30-05:00"
end_date = "2022-12-01T19:00-05:00"

[params.venue]
name = "Hotel Camino Real Monterrey"
street = "Av. Diego Rivera 2492"
city = "San Pedro Garza García"
region = "NL"
zipcode = "66200"
country = "Mexico"

# Navigation button
[params.navigation_button]
enable = false
label = "BOLETOS"
link = "/dataday/tickets"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/RevistaSG"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/c/softwareguru"

[[params.social]]
icon = "fab fa-slack"
link = "https://istio.slack.com"

[[params.social]]
icon = "tf-ion-social-octocat"
link = "https://github.com/softwareguru"

[[params.social]]
icon = "tf-ion-android-mail"
link = "mailto:eventos@sg.com.mx"

[[params.footer_about]]
name = "Istio website"
link = "https://istio.io"

[[params.footer_resources]]
name = "Organizers"
link = "/istiocon-2021/organizers"

[[params.footer_resources]]
name = "Code of Conduct"
link = "/istiocon-2021/coc"

[[params.footer_resources]]
name = "Privacy policy"
link = "/istiocon-2021/privacy"

[[params.footer_resources]]
name = "Call for papers"
link = "https://sessionize.com/istiocon-2021/"

[[params.footer_resources]]
name = "Partnership opportunities"
link = "/istiocon-2021/partner/IstioCon2021_Partner_Packages_v2.pdf"



############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link ="/plugins/color-switcher-design/color-switcher-design.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "/plugins/flaticon/flaticon.css"



# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.slim.min.js" 

[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="https://kit.fontawesome.com/2e09285ae6.js"

[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"

