
######################## default configuration ####################
baseURL = "https://sg.com.mx/dataday/"
publishDir = "public/dataday"
title = "Data Day Monterrey 2022"
enableRobotsTXT = true
RemovePathAccents = true


googleAnalytics = "UA-21077034-25"

theme = "dataday"
# post pagination
paginate = "10"

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


############################## navigation ###############################
[menu]


  [[menu.main]]
  name = "Agenda"
  URL = "agenda"
  weight = 2

 
  #[[menu.main]]
  #name = "Tickets"
  #URL = "tickets/"
  #weight = 3

  #[[menu.main]]
  #name = "Conferencistas"
  #URL = "speakers"
  #weight = 3

  [[menu.main]]
  name = "Data Live"
  URL = "datalive"
  weight = 5

  #[[menu.main]]
  #name = "Kit Virtual"
  #URL = "kitvirtual"
  #weight = 4

  #[[menu.main]]
  #name = "Networking"
  #URL = "networking"
  #weight = 4

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 6

  #[[menu.main]]
  #name = "Tickets"
  #URL = "tickets"
  #weight = 5



#################### default parameters ################################
[params]
logo = "images/dataday2022.png"
home = "Home"

# Meta data
description = "Data Day(s) es el congreso líder de ciencia e ingeniería de datos en México con tres tracks: data MBA, hard core machine learning, e ingeniería de datos."
image = "images/card-2022.jpg"
images = ["images/card-2022.jpg"]
twitter_user = "@revistasg"
email = "eventos@sg.com.mx"
author = "Software Guru"

disclaimer = ""

# Navigation button
[params.navigation_button]
enable = false
label = "Live"
link = "/datadays/live/"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/RevistaSG"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/c/softwareguru"

[[params.social]]
icon = "fab fa-slack"
link = "https://istio.slack.com"

[[params.social]]
icon = "tf-ion-social-octocat"
link = "https://github.com/softwareguru"

[[params.social]]
icon = "tf-ion-android-mail"
link = "mailto:eventos@sg.com.mx"

[[params.footer_about]]
name = "Istio website"
link = "https://istio.io"

[[params.footer_resources]]
name = "Organizers"
link = "/istiocon-2021/organizers"

[[params.footer_resources]]
name = "Code of Conduct"
link = "/istiocon-2021/coc"

[[params.footer_resources]]
name = "Privacy policy"
link = "/istiocon-2021/privacy"

[[params.footer_resources]]
name = "Call for papers"
link = "https://sessionize.com/istiocon-2021/"

[[params.footer_resources]]
name = "Partnership opportunities"
link = "/istiocon-2021/partner/IstioCon2021_Partner_Packages_v2.pdf"



############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link ="/plugins/color-switcher-design/color-switcher-design.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "/plugins/flaticon/flaticon.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"



# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.slim.min.js" 

[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="https://kit.fontawesome.com/2e09285ae6.js"

[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"


